on:
  pull_request:
    branches:
    - master

  push:
    branches:
    - fix-btcec-name

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: command
      run: bash ./.gha.gofmt.sh

    - name: command
      run: bash ./.gha.gotest.sh
